### ISSUE TITLE
Sleep times after midnight

### ISSUE THREAD

**Issue by wunderk** [shashidarette/ProcessingPAL#2]
I came across a problem while trying the program with activPAL data from a participant who went to bed after midnight. It looks like the sleep times are correctly identified in the summary.csv file and the data appears correct in the heat map, but the summary panel shows different numbers and the output in the All .csv file is not always correct (i.e., the incorrect bouts are being summed for the output). Since the sleep bouts are correctly identified but there is no way to make a correction specifying the day the bout belongs to, I am unable to fix it that way. 
Have you come across this issue before? Is there a way for the program to analyze a day with a sleep time that starts on the next calendar day? Based on the Winkler et al. 2016 paper that was referenced in the manual, it sounds like this may be due to looking at the data as a 24-hour day rather than a waking wear day, but I wanted to double check if there was a solution since it seems likely that you would have come across the bedtime past midnight issue previously.

**Comment by shashidarette** [comment]
Thank you @wunderk for sharing the observation.

@CharlotteEd Please share your views on the issue.

Thanks,
Shashidar

**Comment by CharlotteEd** [comment]
Hi @wunderk 
In terms of your query do you mean that if a person goes to bed at 2am, for example, that the data from midnight to 2am is being classified with the day that starts at midnight rather than taking it as part of the previous day? If that is the case, it's not a problem with the software and the calculations are correct, it's a decision that we made to calculate outputs i.e., from midnight to midnight rather than from wake to wake. However, if a bout spans midnight the whole bout will be counted in the previous day but anything from when this bout finishes until sleep will be counted in the next day (i.e., the one after midnight). We will update the instructions to make users aware of this and to provide more information on the decisions behind the calculation of the outputs. Thanks for your feedback.

**Comment by shashidarette** [comment]
Hi @wunderk 

Request you to confirm if your query is clarified?

Thanks.

**Comment by wunderk** [comment]
Hello, 

Yes, thank you for the reminder. Your response provided the information that I was looking for. Thank you for your help.
