### ISSUE TITLE
Variable times and Hour by Hour output

### ISSUE THREAD

**Issue by StephChappel** [shashidarette/ProcessingPAL#3]
Hi

I have been using your ProcessingPAL software and I had a question regarding generating outputs.

I am working with data from emergency nurses completing shift work. I have entered the shift times of interest into the VariableTimes.csv and have been able to extract that information for the total shift time. However, I am interested in the hourly data as well and was wondering if there was a way to make the variable times apply to the ‘hour by hour’ data output? 

I understand if this is not yet a feature of the software.

Thanks
Steph Chappel

**Comment by CharlotteEd** [comment]
Hi Steph,

Thanks for your message. Unfortunately at the moment this is not possible so you will only be able to get the hour by hour data on the hour rather than on specific start and end times that don't start and finish on the hour. At the moment we are working on a number of additional features for the next release of the software but at the moment this isn't one. That's not saying that it won't be on the wish list for the future though! 

Hope you are finding the software useful for your research.

Thanks,

Charlotte

**Comment by StephChappel** [comment]
Hi Charlotte,

Thank you for such a fast response. No worries at all.

I am really enjoying using the software.

Thanks

Steph

**Comment by shashidarette** [comment]
Hi Stephan,

As Charlotte mentioned, we have added the requested feature into the backlog for a future release.

For your information, we have released a new version [V1.2](https://github.com/UOL-COLS/ProcessingPAL/releases/tag/V1.2) with other updates. Please check it out.

Thanks.
