### ISSUE TITLE
VANE vs CREA

### ISSUE THREAD

**Issue by MarshaSport** [shashidarette/ProcessingPAL#7]
Hi, 

Just wanted to point out for anyone else running into problems with this, but when you export the .datx file from PALAnalysis to .csv it's necessary to make sure that the VANE output format is selected (under 'settings'). ProcessingPAL cannot cope with the CREA output because it has decimals (i.e., 3.1 for "lying down" etc.). Can you please add this to the manual as currently no instructions on it. 

Thanks, Marsha

**Comment by shashidarette** [comment]
Thanks @MarshaSport for your input. We will try to incorporate them as a note in instructions/manual in the future version.

From Charlotte: "There aren't any issues with the software in relation to this. It's because PAL technologies who make the activPAL have released a programme which enables the distinction between sitting and lying therefore if users output this file it won't work with ProcessingPAL. It's not a problem because as you can create a normal version of the output file too."
